### ISSUE TITLE
Compile error in sonic-swss/orchagent/orchdaemon.cpp for 202205 branch  

### ISSUE THREAD

**Issue by vmittal-msft** [sonic-net/sonic-swss#2682]
![image](https://user-images.githubusercontent.com/46945843/221683034-74526c1a-2e0b-40d7-8051-c1b0c6bb5df3.png)

This is blocking new PRs - https://github.com/sonic-net/sonic-swss/pull/2618
When i compile locally, it is fine. Only happening in PR Az pipeline.

**Comment by saiarcot895** [comment]
Recent runs in sonic-swss-common for the 202205 branch have been failing vstest (the deb packages are built, though). Because of this, azure pipeline is taking the artifacts from the most recent fully successful run, which is prior to sonic-net/sonic-swss-common@16ff68975a56d37635c3da9c57c8240354cc0088 (which the current version of sonic-swss 202205 branch needs).

There are two options here:

1. Revert 380f72b892baee8978758cc6695895a3d37c232c from the 202205 branch.
2. Allow azure pipeline to get artifacts even from partially successful/failed builds. Note that this may increase the number of pipeline failures for sonic-swss, even though the problem may be elsewhere. I have a draft PR for this at #2683.

**Comment by xumia** [comment]
It may be a little aggressive to download the artifacts from the failed build. A PR to build the sonic-swss-common directly, is it good for it?
https://github.com/sonic-net/sonic-swss/pull/2685

**Comment by saiarcot895** [comment]
Yeah that might be better, particularly if it doesn't take long to build it.
